#!/bin/bash

TEMPLATE_PATH=$HOME/new/src/templates

if [ "$TYPE" == "node-ts" ]; then
  echo "Creating a new Node.js with typescript project" &&

  mkdir $PROJECT_NAME &&
  cd $PROJECT_NAME &&

  npm init -y &&
  npm pkg set scripts.dev="ts-node src/index.ts" &&
  npm pkg set scripts.build="tsc" &&

  yarn add typescript ts-node @types/node &&
  cp $TEMPLATE_PATH/tsconfig.template ./tsconfig.json &&

  mkdir src &&
  echo "console.log('Hello, World!');" >src/index.ts &&
  cd .. &&
  echo "Project created successfully"
fi